version: 1.0.0.{build}
branches:
  only:
  - master

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: >-
    cd Src
    nuget restore
    cd ..

clone_depth: 1
