version: 1.0.8.{build}
branches:
  only:
  - master

build:
  project: Src/CSharpRefImpl.sln

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd:
    - cd Src
    - nuget restore CSharpRefImpl.sln
    - cd ..
    - choco install opencover.portable
    - choco install codecov

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%/xunit.console.x86.exe" -targetargs:"./Src/CSharpModel.Tests/bin/Debug/CSharpRefImpl.CSharpModel.Tests.dll -noshadow" -filter:"+[CSharpModel*]* -[CSharpModel.Tests*]*" -output:"./CSharpRefImpl.xml"
  - codecov -f "CSharpRefImpl.xml"

clone_depth: 1

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2c818e8f3bef6a6759ef
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
