version: 1.0.8.{build}
branches:
  only:
  - master

environment:
  matrix:
    - solution_name: Src/Dogen.TestModels.sln

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: >-
    cd Src

    nuget restore

    cd ..

clone_depth: 1

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6954fae540d73da033b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
