language: csharp
solution: Src/CSharpRefImpl.CSharpRefImpl.sln
mono: alpha

install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Src/CSharpRefImpl.CSharpRefImpl.sln

script:
  - xbuild ./Src/CSharpRefImpl.CSharpRefImpl.sln
  - mono ./Src/packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Src/CSharpRefImpl.CSharpModel.Tests/bin/Debug/CSharpRefImpl.CSharpModel.Tests.dll

notifications:
  email:
    recipients:
      - marco.craveiro@gmail.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aaf7b93c2eeb0c07a5e
    on_success: always
    on_failure: always
