language: csharp
solution: Src/Dogen.TestModels.sln
mono: alpha

notifications:
  email:
    recipients:
      - marco.craveiro@gmail.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aaf7b93c2eeb0c07a5e
    on_success: always
    on_failure: always
