#!/bin/bash

#
# Quick hack to rename files generated by converter. The problem at
# the moment is that filenames with multiple extensions don't work too
# well with CMake. So, to make things easier, we end up generating
# incorrect file names from conversion, and then massage them using
# this script.
#
# To convert models:
# - delete all JSON models: rm *json
# - run convert script
# - run this script.
# - run jq on generated files.

jq . Masd.CSharpRefImpl.CSharpModel.dia.json > Masd.CSharpRefImpl.CSharpModel.json
rm Masd.CSharpRefImpl.CSharpModel.dia.json

jq . Masd.CSharpRefImpl.DirectorySettings.dia.json > Masd.CSharpRefImpl.DirectorySettings.json
rm Masd.CSharpRefImpl.DirectorySettings.dia.json

jq . Masd.CSharpRefImpl.LamModel.dia.json > Masd.CSharpRefImpl.LamModel.json
rm Masd.CSharpRefImpl.LamModel.dia.json
